//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введено имя пользователя или пароль.
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин.
        /// </summary>
        internal static string SignInLoginRequired {
            get {
                return ResourceManager.GetString("SignInLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string SignInPasswordRequired {
            get {
                return ResourceManager.GetString("SignInPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение не совпадает с паролем.
        /// </summary>
        internal static string SignUpConfirmPasswordCompare {
            get {
                return ResourceManager.GetString("SignUpConfirmPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль еще раз.
        /// </summary>
        internal static string SignUpConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("SignUpConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите e-mail верного формата.
        /// </summary>
        internal static string SignUpEmailEmailAddress {
            get {
                return ResourceManager.GetString("SignUpEmailEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот e-mail уже зарегистрирован.
        /// </summary>
        internal static string SignUpEmailRemote {
            get {
                return ResourceManager.GetString("SignUpEmailRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите e-mail.
        /// </summary>
        internal static string SignUpEmailRequired {
            get {
                return ResourceManager.GetString("SignUpEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email должен содержать до {1} символов.
        /// </summary>
        internal static string SignUpEmailStringLength {
            get {
                return ResourceManager.GetString("SignUpEmailStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин может состоять только из латинских символов, цифр, одинарного дефиса или знака подчеркивания.
        /// </summary>
        internal static string SignUpLoginRegularExpression {
            get {
                return ResourceManager.GetString("SignUpLoginRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот логин уже используется.
        /// </summary>
        internal static string SignUpLoginRemote {
            get {
                return ResourceManager.GetString("SignUpLoginRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, укажите логин.
        /// </summary>
        internal static string SignUpLoginRequired {
            get {
                return ResourceManager.GetString("SignUpLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин должен содержать от {2} до {1} символов.
        /// </summary>
        internal static string SignUpLoginStringLength {
            get {
                return ResourceManager.GetString("SignUpLoginStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль содержит запрещённые символы.
        /// </summary>
        internal static string SignUpPasswordRegularExpression {
            get {
                return ResourceManager.GetString("SignUpPasswordRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести пароль.
        /// </summary>
        internal static string SignUpPasswordRequired {
            get {
                return ResourceManager.GetString("SignUpPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать от {2} до {1} символов.
        /// </summary>
        internal static string SignUpPasswordStringLength {
            get {
                return ResourceManager.GetString("SignUpPasswordStringLength", resourceCulture);
            }
        }
    }
}
